name: drug-discovery
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - deepchem
      - scikit-learn
      - xgboost
      - umap-learn
      - shap
      - seaborn
      - matplotlib
      - pandas
      - numpy
      - jupyterlab
      - ipykernel